# Generated by Django 3.2.4 on 2021-06-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('address_extra', models.CharField(max_length=200)),
                ('user_bio', models.TextField(max_length=5000)),
                ('user_img', models.ImageField(upload_to='static/images/user')),
            ],
        ),
    ]
