# Generated by Django 3.2.4 on 2021-07-02 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id_numbe',
            field=models.IntegerField(unique=True),
        ),
    ]
