# Generated by Django 3.2.4 on 2021-07-02 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('student', '0002_alter_student_id_numbe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='depertment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='department.department'),
        ),
    ]
